### ISSUE TITLE
WFS data not loading

### ISSUE THREAD

**Issue by lovesmall** [Oslandia/cesium-buildings#2]
I follow the previous 3D workshop and Cuardo is working ok. I then try the Cesium with the same server running but looks like the WFS returns empty data. So i'm not sure is there any changes need to be done in the database for the cesium building ?

More detail about the issue:

one example of the WFS reqeust (I changed the name of tows from "**textured_citygml_lat_long**" into "**textured_citygml**", as "**textured_citygml_lat_long**" doesn't exist in my db. )
```
localhost/cgi-bin/tinyows?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&outputFormat=JSON&typeName=tows:textured_citygml&srsName=EPSG:4326&BBOX=4.872436523437488,45.7470703125,4.877929687500004,45.7525634765625
```
all of them recieved:
```json
{"type": "FeatureCollection", "crs":{"type":"name","properties":{"name":"EPSG:4326"}}, "features": []}
```

But if I remove the BBOX para, the request will return me a big data set of json.

**Comment by vmora** [comment]
lat_lon like in wgs84. You have to use ST_Transform to create a layer in your db that is in epsg 4326.

**Comment by lovesmall** [comment]
Thanks for the info.
