### ISSUE TITLE
tinyows return empty feature array (ST_AsGeoJSON doesnot support polyhedral surface) 

### ISSUE THREAD

**Issue by Vinni0803** [Oslandia/cesium-buildings#5]
Cesium Building requires data in GeoJson format and its sends wfs getfeature request with parameter outputFormat=JSON.

For this request tinyows run's a query on postgis to get data in GeoJson format. But it mentioned on postgis site that st_AsGeoJson does not support polyhedral surface, so for  query postgis gives an error.

But your example is working fine, its sends getFeature request and in response tinyows return json. 

**I'm not able to understand how its working in your case. Have you done something specific for this in tinyows, postgis or at server , as postgis does not return json for polyhedral surface.**

  WFS request : http://localhost:19090/WFS?SERVICE=WFS&VERSION=1.0.0&REQUEST=GetFeature&outputFormat=JSON&typeName=tows:levkreuz&srsName=EPSG:31466&BBOX=2569730.6565833003,5657887.107612559,2570155.6946951896,565831

Result  : {type: "FeatureCollection", crs: {type: "name", properties: {name: "EPSG:31466"}}, features: []}
empty features array.

Here the query  : http://gis.stackexchange.com/questions/193281/lwgeom-to-geojson-polyhedralsurface-geometry-type-not-supported

  I'm using postgis 2.2.2, TinyOWS version:   1.1.0

**Comment by Jeremy-Gaillard** [comment]
Hello,

We use a custom version of postgis and TinyOWS that support polyhedral surfaces.
Here are the changes required to add the support if you want to try them out:
- [PostGIS](https://github.com/Jeremy-Gaillard/postgis/commit/07167d67cfc16945f4b0d4b878e0d30453b2aae1)
- [TinyOWS](https://github.com/Jeremy-Gaillard/tinyows/commit/9890118e5300326db405f6b766fc8ee7b15cd819)

**Comment by Vinni0803** [comment]
@Jeremy-Gaillard : Thanx !

**Comment by Vinni0803** [comment]
@Jeremy-Gaillard : Its working for me. 

There is one more thing which I want to know, are you using the same cesium building lib present here <https://github.com/Oslandia/cesium-buildings> or you have made some changes to it. As in my case its sending request for wfs getCapabilities after that its not sending the getFeature request. But i have made a small change in tileProvider.js, after which it's sending the request for getFeature but only 4-9 request only.

So its not showing all (for lyon or berlin) data on map.

**Comment by Jeremy-Gaillard** [comment]
It's been a while since we last used cesium buildings (especially the master branch). 

The bug you mention may come from the web workers crashing while reading the geometry (see createWfsGeometry.js). Workers tend to fail silently. You could try adding log messages at the start and end of the procedure (l.467 and l.519 for example) or a try/catch statement to see if a problem occurs.

**Comment by Vinni0803** [comment]
@Jeremy-Gaillard :  i am trying to add textures to buildings . I have provided the textureBaseUrl in WfsTileProvider but application is not showing any textures , errors or any request for textures in network.

**Comment by Jeremy-Gaillard** [comment]
Texture aren't supported in the current version of the master.

Here are the steps required to enable them:
- Fix texture coordinate computation (st) in geomFromWfsPolyhedralSurface
- Change material type and add textures url to the geometries [here](https://github.com/Oslandia/cesium-buildings/blob/master/js/TileProvider.js#L613). [Material fabric documentation](https://github.com/AnalyticalGraphicsInc/cesium/wiki/Fabric).
- Change the shaders to support textures

**Comment by neelesh33** [comment]
Hi Jeremy,
In which branch texture is supported ?

**Comment by Jeremy-Gaillard** [comment]
Hi,

According to the commit history, this is the last commit where the textures are supported: https://github.com/Oslandia/cesium-buildings/tree/1086e4600a49e2e495d2244a3d36edd46ac0f758

However, this version is pretty old and does not support polyhedral surfaces.  It is also far less polished than the actual version.
